kind: pipeline
name: default

clone:
  disable: true


steps:
  - name: clone
    image: plugins/git
    recursive: true

  # Production build and deploy
  - name: build
    image: klakegg/hugo
    commands:
      - hugo version
      - hugo --minify
    environment:
      HUGO_ENV: production
    when:
      branch:
        - master

  - name: deploy
    image: appleboy/drone-scp
    settings:
      source: public/*
      strip_components: 1 # Make sure the tarball doesn't contain leading path
      rm: true # Make sure only the newly generated files are left
      host:
        from_secret: ssh_host
      target:
        from_secret: ssh_target
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
    when:
      branch:
        - master

  # Dev build and deploy
  - name: build-dev
    image: klakegg/hugo
    commands:
      - hugo version
      # Include drafts and future articles, use dev base url
      - hugo --minify -D -F -b https://dev.belanyi.fr
    when:
      branch:
        exclude:
          - master

  - name: deploy-dev
    image: appleboy/drone-scp
    settings:
      source: public/*
      strip_components: 1 # Make sure the tarball doesn't contain leading path
      rm: true # Make sure only the newly generated files are left
      host:
        from_secret: ssh_host
      target:
        from_secret: ssh_target_dev
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
    when:
      branch:
        exclude:
          - master
