baseURL: "https://belanyi.fr/"
languageCode: "en-us"
title: "Ambroisie's blog"

theme: "anubis"
paginate: 5
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0

author:
  name: "Bruno BELANYI"
  email: "bruno@belanyi.fr"
  github: "Ambroisie"
  gitlab: "Ambroisie"
  sourcehut: "ambroisie"
  linkedin: "bruno-belanyi"
  matrix: "@ambroisie:belanyi.fr"

permalinks:
  posts: /:year/:month/:day/:title/


params:
  author: "Bruno BELANYI"
  description: "A simple blog about programmation"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto-without-switcher

taxonomies:
  category: "categories"
  tag: "tags"
  serie: "series"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
