baseURL: "https://belanyi.fr/"
languageCode: "en-us"
title: "Ambroisie's blog"

theme:
  - "hugo-atom-feed"
  - "anubis"
paginate: 5
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0
  - identifier: categories
    name: Categories
    title: Categories
    url: /categories/
    weight: 0

author:
  name: "Bruno BELANYI"
  email: "contact-blog@belanyi.fr"
  github: "ambroisie"
  gitlab: "ambroisie"
  sourcehut: "ambroisie"
  linkedin: "bruno-belanyi"
  matrix: "@ambroisie:belanyi.fr"
  mastodon: "nixos.paris/@ambroisie"

permalinks:
  posts: /:year/:month/:day/:title/

outputs:
  # <domain>/atom.xml
  home: [ "HTML", "RSS", "ATOM" ]
  # <domain>/posts/atom.xml
  section: [ "HTML", "RSS", "ATOM" ]
  # <domain>/tags/mytag/atom.xml
  taxonomy: [ "HTML", "RSS", "ATOM" ]

ignoreErrors:
  - "error-output-taxonomy"

params:
  author: "Bruno BELANYI"
  description: "A simple blog about programmation"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto-without-switcher
  webmentions:
    login: belanyi.fr
    pingback: true
  mathjax: true

services:
  disqus:
    shortname: ""
  googleAnalytics:
    ID: ""

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
